import 'dart:io';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../models/settlement.dart';
import '../models/settlement_account.dart';

class PdfService {
  static Future<void> shareSettlementPdf({
    required Settlement settlement,
    required String creditorName,
    required String debtorName,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text("Financial Settlement Report", style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                    pw.Text("Manazel App", style: const pw.TextStyle(color: PdfColors.grey)),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text("Report Date: ${DateTime.now().day}/${DateTime.now().month}/${DateTime.now().year}"),
                      pw.Text("Transaction Date: ${settlement.date.day}/${settlement.date.month}/${settlement.date.year}"),
                    ],
                  ),
                  pw.Container(
                    padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 5),
                    decoration: pw.BoxDecoration(
                      color: settlement.status == 'paid' ? PdfColors.green : PdfColors.orange,
                      borderRadius: const pw.BorderRadius.all(pw.Radius.circular(5)),
                    ),
                    child: pw.Text(
                      settlement.status.toUpperCase(),
                      style: pw.TextStyle(color: PdfColors.white, fontWeight: pw.FontWeight.bold),
                    ),
                  ),
                ],
              ),
              pw.SizedBox(height: 20),
              pw.Divider(),
              pw.SizedBox(height: 20),
              _buildSectionTitle("Parties Involved"),
              pw.Row(
                children: [
                  pw.Expanded(child: _buildInfoBox("Creditor", creditorName)),
                  pw.SizedBox(width: 20),
                  pw.Expanded(child: _buildInfoBox("Debtor", debtorName)),
                ],
              ),
              pw.SizedBox(height: 30),
              _buildSectionTitle("Financial Details"),
              pw.Table(
                border: pw.TableBorder.all(color: PdfColors.grey300),
                children: [
                  _buildTableRow("Original Amount", "${NumberFormat("#,##0.00").format(settlement.amount)} SAR"),
                  _buildTableRow("Total Paid", "${NumberFormat("#,##0.00").format(settlement.totalPaid)} SAR"),
                  _buildTableRow("Remaining Amount", "${NumberFormat("#,##0.00").format(settlement.remainingAmount)} SAR", isBold: true),
                ],
              ),
              pw.SizedBox(height: 30),
              _buildSectionTitle("Description"),
              pw.Container(
                padding: const pw.EdgeInsets.all(10),
                decoration: pw.BoxDecoration(
                  border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey300)),
                ),
                child: pw.Text(settlement.description, style: const pw.TextStyle(fontSize: 12)),
              ),
              pw.Spacer(),
              pw.Divider(),
              pw.Align(
                alignment: pw.Alignment.center,
                child: pw.Text("This is an official financial report generated by Manazel App", style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
              ),
            ],
          );
        },
      ),
    );

    final output = await getTemporaryDirectory();
    final fileName = "Settlement_${settlement.id}_${DateTime.now().millisecondsSinceEpoch}.pdf";
    final file = File("${output.path}/$fileName");
    await file.writeAsBytes(await pdf.save());

    await Share.shareXFiles([XFile(file.path)], text: "Financial Settlement Report - $creditorName to $debtorName");
  }

  static pw.Widget _buildSectionTitle(String title) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 10),
      child: pw.Text(title, style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: PdfColors.blueGrey800)),
    );
  }

  static pw.Widget _buildInfoBox(String label, String value) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(5)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(label, style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
          pw.Text(value, style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
  }

  static pw.TableRow _buildTableRow(String label, String value, {bool isBold = false}) {
    return pw.TableRow(
      children: [
        pw.Padding(
          padding: const pw.EdgeInsets.all(8),
          child: pw.Text(label, style: pw.TextStyle(fontWeight: isBold ? pw.FontWeight.bold : pw.FontWeight.normal)),
        ),
        pw.Padding(
          padding: const pw.EdgeInsets.all(8),
          child: pw.Text(value, style: pw.TextStyle(fontWeight: isBold ? pw.FontWeight.bold : pw.FontWeight.normal), textAlign: pw.TextAlign.right),
        ),
      ],
    );
  }

  static Future<void> shareAccountPdf({
    required SettlementAccount account,
    required List<Settlement> settlements,
    required Map<String, dynamic> summary,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text("Account Statement", style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                  pw.Text("Manazel App", style: const pw.TextStyle(color: PdfColors.grey)),
                ],
              ),
            ),
            pw.SizedBox(height: 20),
            pw.Text("Account Name: ${account.name}"),
            pw.Text("Account Type: ${account.type.toUpperCase()}"),
            pw.Text("Generated on: ${DateTime.now().day}/${DateTime.now().month}/${DateTime.now().year}"),
            pw.SizedBox(height: 20),
            pw.Divider(),
            pw.SizedBox(height: 20),
            _buildSectionTitle("Summary"),
            pw.Row(
              children: [
                pw.Expanded(child: _buildInfoBox("Due to You", "${summary['totalDueToMe']} SAR")),
                pw.SizedBox(width: 10),
                pw.Expanded(child: _buildInfoBox("You Owe", "${summary['totalIOwe']} SAR")),
                pw.SizedBox(width: 10),
                pw.Expanded(child: _buildInfoBox("Balance", "${summary['remaining']} SAR")),
              ],
            ),
            pw.SizedBox(height: 30),
            _buildSectionTitle("Operations History"),
            pw.Table(
              border: pw.TableBorder.all(color: PdfColors.grey300),
              columnWidths: {
                0: const pw.FixedColumnWidth(80),
                1: const pw.FlexColumnWidth(),
                2: const pw.FixedColumnWidth(60),
                3: const pw.FixedColumnWidth(80),
              },
              children: [
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                  children: [
                    _buildTableCell("Date", isHeader: true),
                    _buildTableCell("Description", isHeader: true),
                    _buildTableCell("Type", isHeader: true),
                    _buildTableCell("Amount", isHeader: true),
                  ],
                ),
                ...settlements.map((s) => pw.TableRow(
                  children: [
                    _buildTableCell("${s.date.day}/${s.date.month}/${s.date.year}"),
                    _buildTableCell(s.description),
                    _buildTableCell(s.direction == 'to_me' ? "IN" : "OUT"),
                    _buildTableCell("${NumberFormat("#,##0.00").format(s.amount)} SAR"),
                  ],
                )),
              ],
            ),
          ];
        },
      ),
    );

    final output = await getTemporaryDirectory();
    final fileName = "Account_${account.name}_${DateTime.now().millisecondsSinceEpoch}.pdf";
    final file = File("${output.path}/$fileName");
    await file.writeAsBytes(await pdf.save());

    await Share.shareXFiles([XFile(file.path)], text: "Account Statement - ${account.name}");
  }

  static pw.Widget _buildTableCell(String text, {bool isHeader = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(5),
      child: pw.Text(
        text,
        style: pw.TextStyle(fontWeight: isHeader ? pw.FontWeight.bold : pw.FontWeight.normal, fontSize: 10),
      ),
    );
  }
}
