-- ============================================================================
-- Manazel — Phase 3: Operational Money Flow
-- Suppliers, Purchase Invoices, Pending Expenses, Shared Expenses.
--
-- Design reference: docs/database_architecture/supabase_schema_design.md
-- Sections 7-8. Depends on Phase 1 (hotels, profiles, is_hotel_accessible,
-- has_permission, has_any_permission) and Phase 2 (financial_categories,
-- financial_report_expense_lines).
--
-- This migration also backfills the two columns Phase 2 deliberately left
-- out because their FK targets didn't exist yet:
--   financial_report_expense_lines.pending_expense_id -> pending_expenses(id)
--   financial_report_expense_lines.supplier_id         -> suppliers(id)
-- `financial_reports.filed_by_employee_id` is still deferred — employees
-- doesn't exist until Phase 4.
--
-- Creation order matters here: suppliers has no forward dependency, so it
-- goes first; shared_expense_groups before pending_expenses (which links
-- back to it); pending_expenses before shared_expense_allocations is NOT
-- required (allocations only reference groups+hotels) but is kept adjacent
-- to its group for readability.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. suppliers
-- ----------------------------------------------------------------------------
create table suppliers (
  id uuid primary key default gen_random_uuid(),
  hotel_id uuid not null references hotels(id) on delete cascade,
  official_name text not null,
  short_name text not null,
  tax_number text not null,
  default_category_id uuid references financial_categories(id),
  notes text,
  archived_at timestamptz,
  archived_by uuid references profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references profiles(id),
  updated_by uuid references profiles(id),
  unique (hotel_id, tax_number)
);
create trigger trg_suppliers_updated_at before update on suppliers
  for each row execute function set_updated_at();
create index idx_suppliers_hotel on suppliers(hotel_id) where archived_at is null;
create index idx_suppliers_name_trgm on suppliers using gin (official_name gin_trgm_ops);

-- ----------------------------------------------------------------------------
-- 2. shared_expense_groups + shared_expense_allocations
-- One shared cost, paid up front by funding_hotel_id, split across several
-- hotels — each allocation becomes a real pending_expense on that hotel
-- (Section 3 below), not just a number on a shared record.
-- ----------------------------------------------------------------------------
create table shared_expense_groups (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references financial_categories(id),
  description text,
  total_amount numeric(14,2) not null check (total_amount > 0),
  payment_method text not null check (payment_method in ('cash','pos','bank_transfer')),
  funding_hotel_id uuid not null references hotels(id),
  expense_date date not null,
  created_at timestamptz not null default now(),
  created_by uuid references profiles(id)
);
create index idx_shared_expense_groups_funding_hotel on shared_expense_groups(funding_hotel_id, expense_date desc);

create table shared_expense_allocations (
  id uuid primary key default gen_random_uuid(),
  shared_expense_group_id uuid not null references shared_expense_groups(id) on delete cascade,
  hotel_id uuid not null references hotels(id),
  amount numeric(14,2) not null check (amount > 0),
  created_at timestamptz not null default now(),
  unique (shared_expense_group_id, hotel_id)
);
create index idx_shared_alloc_group on shared_expense_allocations(shared_expense_group_id);
create index idx_shared_alloc_hotel on shared_expense_allocations(hotel_id);

-- ----------------------------------------------------------------------------
-- 3. pending_expenses (+ attachments)
-- payment_method here is the hotel's OWN funding options (an amount funded
-- by another hotel is expressed via funding_source_hotel_id instead, same
-- convention as the existing app). shared_expense_group_id is set only for
-- rows auto-generated by create_shared_expense_distribution() (Section: RPCs).
-- ----------------------------------------------------------------------------
create table pending_expenses (
  id uuid primary key default gen_random_uuid(),
  hotel_id uuid not null references hotels(id) on delete cascade,
  category_id uuid not null references financial_categories(id),
  supplier_id uuid references suppliers(id),
  amount numeric(14,2) not null check (amount > 0),
  statement text not null,
  payment_method text not null check (payment_method in ('cash','pos','personal','owner_drawing','deferred')),
  funding_source_hotel_id uuid references hotels(id),
  due_date date,
  is_transferred boolean not null default false,
  transferred_at timestamptz,
  shared_expense_group_id uuid references shared_expense_groups(id) on delete set null,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references profiles(id),
  updated_by uuid references profiles(id)
);
create trigger trg_pending_expenses_updated_at before update on pending_expenses
  for each row execute function set_updated_at();
create index idx_pending_expenses_hotel on pending_expenses(hotel_id, is_transferred) where archived_at is null;
create index idx_pending_expenses_category on pending_expenses(category_id);
create index idx_pending_expenses_shared_group on pending_expenses(shared_expense_group_id);

create table pending_expense_attachments (
  id uuid primary key default gen_random_uuid(),
  pending_expense_id uuid not null references pending_expenses(id) on delete cascade,
  storage_path text not null,
  file_name text not null,
  file_type text not null,
  created_at timestamptz not null default now(),
  created_by uuid references profiles(id)
);

-- ----------------------------------------------------------------------------
-- 4. Backfill Phase 2's deferred columns now that their targets exist.
-- ----------------------------------------------------------------------------
alter table financial_report_expense_lines
  add column pending_expense_id uuid references pending_expenses(id),
  add column supplier_id uuid references suppliers(id);
create index idx_report_expense_lines_pending on financial_report_expense_lines(pending_expense_id);

-- ----------------------------------------------------------------------------
-- 5. invoices (+ attachments, audit log, supplier debt/payment tracking)
-- funding_source_type mirrors the existing app's 5 funding options exactly
-- (kInvoiceFundingSources) — 'deferred_supplier' is the only one requiring
-- a supplier_debts row, created atomically by create_invoice() (Section: RPCs).
-- ----------------------------------------------------------------------------
create table invoices (
  id uuid primary key default gen_random_uuid(),
  hotel_id uuid not null references hotels(id) on delete cascade,
  supplier_id uuid not null references suppliers(id),
  invoice_number text not null,
  invoice_date date not null,
  amount_before_tax numeric(14,2) not null,
  vat numeric(14,2) not null,
  total_amount numeric(14,2) not null,
  category_id uuid not null references financial_categories(id),
  funding_source_type text not null check (funding_source_type in ('hotel_safe','owner','other_hotel','personal_expense','deferred_supplier')),
  payment_method text check (payment_method in ('cash','pos','partial')),
  related_hotel_id uuid references hotels(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references profiles(id),
  updated_by uuid references profiles(id),
  unique (hotel_id, supplier_id, invoice_number)
);
create trigger trg_invoices_updated_at before update on invoices
  for each row execute function set_updated_at();
create index idx_invoices_hotel_date on invoices(hotel_id, invoice_date desc);
create index idx_invoices_category on invoices(category_id);
create index idx_invoices_supplier on invoices(supplier_id);
-- Soft duplicate-detection support (the app warns, never hard-blocks, on a
-- likely-duplicate invoice — see findDuplicateInvoice/findDuplicateByContent
-- in the existing local repository; this index just makes that lookup fast,
-- it does not enforce uniqueness itself).
create index idx_invoices_supplier_date_total on invoices(supplier_id, invoice_date, total_amount);

create table invoice_attachments (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references invoices(id) on delete cascade,
  storage_path text not null,
  file_name text not null,
  file_type text not null,
  created_at timestamptz not null default now(),
  created_by uuid references profiles(id)
);

create table invoice_audit_log (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references invoices(id) on delete cascade,
  user_id uuid references profiles(id),
  operation_type text not null check (operation_type in ('create','update','delete')),
  changed_fields jsonb,
  occurred_at timestamptz not null default now()
);

create table supplier_debts (
  id uuid primary key default gen_random_uuid(),
  hotel_id uuid not null references hotels(id) on delete cascade,
  supplier_id uuid not null references suppliers(id),
  invoice_id uuid not null references invoices(id) unique,
  amount numeric(14,2) not null,
  status text not null default 'unpaid' check (status in ('unpaid','partially_paid','paid')),
  created_at timestamptz not null default now()
);
create index idx_supplier_debts_supplier on supplier_debts(supplier_id, status);

create table supplier_payments (
  id uuid primary key default gen_random_uuid(),
  hotel_id uuid not null references hotels(id) on delete cascade,
  supplier_id uuid not null references suppliers(id),
  amount numeric(14,2) not null check (amount > 0),
  method text,
  payment_date date not null,
  notes text,
  created_at timestamptz not null default now(),
  created_by uuid references profiles(id)
);
create index idx_supplier_payments_supplier on supplier_payments(supplier_id, payment_date desc);

-- ----------------------------------------------------------------------------
-- 6. Row Level Security
--
-- The two permission codes referenced below ('suppliers.manage',
-- 'pending_expenses.manage') are cataloged in seed.sql, not here — matching
-- the pattern from every earlier phase (policies may reference a permission
-- code before its catalog row exists; has_permission() just won't grant
-- anyone that permission until the seed inserts it and maps it to a role).
-- ----------------------------------------------------------------------------
alter table suppliers enable row level security;
create policy suppliers_select on suppliers for select using (is_hotel_accessible(hotel_id));
create policy suppliers_write on suppliers for all
  using (is_hotel_accessible(hotel_id) and has_permission(hotel_id, 'suppliers.manage'))
  with check (is_hotel_accessible(hotel_id) and has_permission(hotel_id, 'suppliers.manage'));

alter table pending_expenses enable row level security;
create policy pending_expenses_select on pending_expenses for select using (is_hotel_accessible(hotel_id));
create policy pending_expenses_write on pending_expenses for all
  using (is_hotel_accessible(hotel_id) and has_permission(hotel_id, 'pending_expenses.manage'))
  with check (is_hotel_accessible(hotel_id) and has_permission(hotel_id, 'pending_expenses.manage'));

alter table pending_expense_attachments enable row level security;
create policy pending_expense_attachments_select on pending_expense_attachments for select using (
  exists (select 1 from pending_expenses pe where pe.id = pending_expense_id and is_hotel_accessible(pe.hotel_id))
);
create policy pending_expense_attachments_write on pending_expense_attachments for all using (
  exists (select 1 from pending_expenses pe where pe.id = pending_expense_id
    and is_hotel_accessible(pe.hotel_id) and has_permission(pe.hotel_id, 'pending_expenses.manage'))
) with check (
  exists (select 1 from pending_expenses pe where pe.id = pending_expense_id
    and is_hotel_accessible(pe.hotel_id) and has_permission(pe.hotel_id, 'pending_expenses.manage'))
);

-- A shared expense group is visible to its funding hotel AND every hotel it
-- was allocated to (they need to see why a pending expense appeared). This
-- CANNOT be expressed as two ordinary policies that each EXISTS-query the
-- other table directly: shared_expense_groups_select referencing
-- shared_expense_allocations, whose own select policy references
-- shared_expense_groups back, causes Postgres to report "infinite recursion
-- detected in policy" (found by testing, not theoretical) — the two
-- policies' RLS evaluation is mutually re-triggering. Routing the
-- cross-table check through one `security definer` function breaks the
-- cycle: the function runs with the elevated privilege of whoever owns it
-- (the migration-applying role), which bypasses RLS entirely for the
-- queries INSIDE the function, so evaluating it never re-enters either
-- table's policy.
create or replace function is_shared_expense_group_visible(target_group_id uuid)
returns boolean language plpgsql stable security definer set search_path = public, pg_temp as $$
declare
  v_funding_hotel uuid;
begin
  select funding_hotel_id into v_funding_hotel from shared_expense_groups where id = target_group_id;
  if v_funding_hotel is null then
    return false;
  end if;
  if is_hotel_accessible(v_funding_hotel) then
    return true;
  end if;
  return exists (
    select 1 from shared_expense_allocations a
    where a.shared_expense_group_id = target_group_id and is_hotel_accessible(a.hotel_id)
  );
end;
$$;

alter table shared_expense_groups enable row level security;
create policy shared_expense_groups_select on shared_expense_groups for select using (
  is_shared_expense_group_visible(id)
);
create policy shared_expense_groups_write on shared_expense_groups for all
  using (is_hotel_accessible(funding_hotel_id) and has_permission(funding_hotel_id, 'pending_expenses.manage'))
  with check (is_hotel_accessible(funding_hotel_id) and has_permission(funding_hotel_id, 'pending_expenses.manage'));

alter table shared_expense_allocations enable row level security;
create policy shared_expense_allocations_select on shared_expense_allocations for select using (
  is_hotel_accessible(hotel_id) or is_shared_expense_group_visible(shared_expense_group_id)
);
create policy shared_expense_allocations_write on shared_expense_allocations for all using (
  exists (select 1 from shared_expense_groups g where g.id = shared_expense_group_id
    and is_hotel_accessible(g.funding_hotel_id) and has_permission(g.funding_hotel_id, 'pending_expenses.manage'))
) with check (
  exists (select 1 from shared_expense_groups g where g.id = shared_expense_group_id
    and is_hotel_accessible(g.funding_hotel_id) and has_permission(g.funding_hotel_id, 'pending_expenses.manage'))
);

alter table invoices enable row level security;
create policy invoices_select on invoices for select using (is_hotel_accessible(hotel_id));
create policy invoices_insert on invoices for insert with check (is_hotel_accessible(hotel_id) and has_permission(hotel_id, 'suppliers.manage'));
create policy invoices_update on invoices for update using (is_hotel_accessible(hotel_id) and has_permission(hotel_id, 'suppliers.manage'));
-- No delete policy — invoices are never hard-deleted by any role (tax/audit record).

alter table invoice_attachments enable row level security;
create policy invoice_attachments_select on invoice_attachments for select using (
  exists (select 1 from invoices i where i.id = invoice_id and is_hotel_accessible(i.hotel_id))
);
create policy invoice_attachments_write on invoice_attachments for all using (
  exists (select 1 from invoices i where i.id = invoice_id and is_hotel_accessible(i.hotel_id) and has_permission(i.hotel_id, 'suppliers.manage'))
) with check (
  exists (select 1 from invoices i where i.id = invoice_id and is_hotel_accessible(i.hotel_id) and has_permission(i.hotel_id, 'suppliers.manage'))
);

alter table invoice_audit_log enable row level security;
create policy invoice_audit_log_select on invoice_audit_log for select using (
  exists (select 1 from invoices i where i.id = invoice_id and is_hotel_accessible(i.hotel_id))
);
-- No client write policy — only written by create_invoice()/update paths internally (security invoker, still passes RLS as the calling user, but there is deliberately no direct insert policy for ad-hoc client writes to keep this an honest system trail).
create policy invoice_audit_log_insert on invoice_audit_log for insert with check (
  exists (select 1 from invoices i where i.id = invoice_id and is_hotel_accessible(i.hotel_id) and has_permission(i.hotel_id, 'suppliers.manage'))
);

alter table supplier_debts enable row level security;
create policy supplier_debts_select on supplier_debts for select using (is_hotel_accessible(hotel_id));
create policy supplier_debts_write on supplier_debts for all
  using (is_hotel_accessible(hotel_id) and has_permission(hotel_id, 'suppliers.manage'))
  with check (is_hotel_accessible(hotel_id) and has_permission(hotel_id, 'suppliers.manage'));

alter table supplier_payments enable row level security;
create policy supplier_payments_select on supplier_payments for select using (is_hotel_accessible(hotel_id));
create policy supplier_payments_write on supplier_payments for all
  using (is_hotel_accessible(hotel_id) and has_permission(hotel_id, 'suppliers.manage'))
  with check (is_hotel_accessible(hotel_id) and has_permission(hotel_id, 'suppliers.manage'));
